# Generated by Django 3.1.5 on 2021-04-11 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='latest',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Other Images'),
        ),
        migrations.AddField(
            model_name='latest',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Other Images'),
        ),
        migrations.AddField(
            model_name='latest',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Other Images'),
        ),
        migrations.AlterField(
            model_name='latest',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='uploads/', verbose_name='Image'),
        ),
    ]
