# Generated by Django 3.1.5 on 2021-04-11 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_auto_20210411_2218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='latest',
            old_name='desription',
            new_name='description',
        ),
    ]
