# Generated by Django 3.1.5 on 2021-04-20 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_auto_20210411_2344'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Latest',
        ),
    ]
